// Three.js front end: 3-D embedding space, corpus attributes, search, reader.
//
// Data comes from web/data/corpus3d.json (generated by export_web.py, gitignored
// because it contains book text). Pure data logic lives in core.js.

import * as THREE from "three";
import { OrbitControls } from "three/addons/controls/OrbitControls.js";
import { chapterHue, cosineTopK, extent, formatInt, keywordSearch } from "./core.js";

const DATA_URL = "data/corpus3d.json";
const SVG_NS = "http://www.w3.org/2000/svg";
const el = (id) => document.getElementById(id);

const state = {
  bundle: null, pointsObj: null, baseColors: null,
  selected: null, chapter: null, marker: null, lines: null, tween: null,
  scale: 1, center: { x: 0, y: 0, z: 0 },
};

let renderer, scene, camera, controls, raycaster, pointer;

init();

async function init() {
  let bundle;
  try {
    const res = await fetch(DATA_URL, { cache: "no-store" });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    bundle = await res.json();
  } catch (err) {
    const box = el("error");
    box.hidden = false;
    box.textContent =
      `Could not load ${DATA_URL} — ${err.message}.\n` +
      `Generate it with:  python export_web.py corpus index web/data/corpus3d.json\n` +
      `Then serve this folder over HTTP:  python -m http.server 8502 --directory web`;
    return;
  }
  state.bundle = bundle;
  buildScene(bundle);
  renderMeta(bundle);
  renderChapters(bundle);
  renderCharts(bundle);
  renderHeatmap(bundle);
  wireSearch(bundle);
  wireHud();
  window.addEventListener("resize", onResize);
  animate();
}

/* ------------------------------------------------------------------ scene */

function buildScene(bundle) {
  const canvas = el("scene");
  renderer = new THREE.WebGLRenderer({ canvas, antialias: true });
  renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));

  scene = new THREE.Scene();
  scene.background = new THREE.Color(0x0b0d12);
  scene.fog = new THREE.FogExp2(0x0b0d12, 0.0045);

  camera = new THREE.PerspectiveCamera(55, 1, 0.1, 4000);
  camera.position.set(0, 10, 54);

  controls = new OrbitControls(camera, canvas);
  controls.enableDamping = true;
  controls.dampingFactor = 0.08;
  controls.autoRotateSpeed = 0.7;

  const pts = bundle.points;
  const n = pts.length;
  const pos = new Float32Array(n * 3);
  const col = new Float32Array(n * 3);

  let cx = 0, cy = 0, cz = 0;
  for (const p of pts) { cx += p.x; cy += p.y; cz += p.z; }
  cx /= n; cy /= n; cz /= n;
  let maxR = 1e-9;
  for (const p of pts) {
    const r = Math.hypot(p.x - cx, p.y - cy, p.z - cz);
    if (r > maxR) maxR = r;
  }
  state.scale = 30 / maxR;
  state.center = { x: cx, y: cy, z: cz };

  const c = new THREE.Color();
  pts.forEach((p, i) => {
    const [x, y, z] = scenePos(p);
    pos[i * 3] = x; pos[i * 3 + 1] = y; pos[i * 3 + 2] = z;
    c.setHSL(chapterHue(p.ch - 1) / 360, 0.72, 0.62);
    col[i * 3] = c.r; col[i * 3 + 1] = c.g; col[i * 3 + 2] = c.b;
  });

  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.BufferAttribute(pos, 3));
  geo.setAttribute("color", new THREE.BufferAttribute(col, 3));
  const mat = new THREE.PointsMaterial({
    size: 0.85, vertexColors: true, sizeAttenuation: true,
    transparent: true, opacity: 0.92, depthWrite: false,
  });
  state.pointsObj = new THREE.Points(geo, mat);
  state.baseColors = col.slice();
  scene.add(state.pointsObj);

  raycaster = new THREE.Raycaster();
  raycaster.params.Points.threshold = 0.65;
  pointer = new THREE.Vector2();

  canvas.addEventListener("pointermove", onPointerMove);
  canvas.addEventListener("click", onClick);
  canvas.addEventListener("pointerleave", () => { el("tooltip").hidden = true; });

  el("hud-text").textContent =
    `${formatInt(n)} chunk vectors · ${bundle.vector_dim}-d → 3 via PCA · drag to orbit · scroll to zoom · click a point`;
  onResize();
}

function scenePos(p) {
  return [(p.x - state.center.x) * state.scale,
          (p.y - state.center.y) * state.scale,
          (p.z - state.center.z) * state.scale];
}

function onResize() {
  const canvas = renderer.domElement;
  const w = canvas.clientWidth || window.innerWidth;
  const h = canvas.clientHeight || window.innerHeight;
  renderer.setSize(w, h, false);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}

function animate() {
  requestAnimationFrame(animate);
  if (state.tween) stepTween();
  controls.update();
  renderer.render(scene, camera);
}

/* ------------------------------------------------------------ interaction */

function pick(event) {
  const rect = renderer.domElement.getBoundingClientRect();
  pointer.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
  pointer.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;
  raycaster.setFromCamera(pointer, camera);
  const hit = raycaster.intersectObject(state.pointsObj, false)[0];
  return hit ? hit.index : null;
}

function onPointerMove(event) {
  const id = pick(event);
  const tip = el("tooltip");
  if (id === null) { tip.hidden = true; return; }
  const p = state.bundle.points[id];
  const strong = document.createElement("strong");
  strong.textContent = p.citation;
  const span = document.createElement("span");
  span.textContent = `${p.preview}…`;
  tip.replaceChildren(strong, span);
  tip.hidden = false;
  tip.style.left = `${event.clientX + 14}px`;
  tip.style.top = `${event.clientY + 14}px`;
}

function onClick(event) {
  const id = pick(event);
  if (id !== null) select(id);
}

function select(id) {
  const bundle = state.bundle;
  const p = bundle.points[id];
  state.selected = id;

  const neighbours = cosineTopK(bundle.vectors, bundle.vector_dim, id, 8);
  showMarker(p);
  drawNeighbourLines(p, neighbours);

  const panel = el("detail");
  panel.hidden = false;
  const close = document.createElement("button");
  close.type = "button";
  close.className = "close";
  close.textContent = "close";
  close.addEventListener("click", () => { panel.hidden = true; clearMarker(); });

  const h3 = document.createElement("h3");
  h3.textContent = p.citation;
  const meta = document.createElement("p");
  meta.className = "caption";
  meta.textContent = `${p.words} words · chapter ${p.ch}` +
    (p.page ? ` · starts on page ${p.page}` : "");

  const body = document.createElement("div");
  body.className = "chunk";
  body.textContent = p.text;

  const h4 = document.createElement("h4");
  h4.textContent = "Nearest chunks — cosine over the bge-small vectors, in the browser";
  const list = document.createElement("ol");
  list.className = "list";
  for (const nb of neighbours) {
    const q = bundle.points[nb.id];
    const li = document.createElement("li");
    const btn = document.createElement("button");
    btn.type = "button";
    const score = document.createElement("span");
    score.className = "score";
    score.textContent = nb.score.toFixed(3);
    btn.append(score, document.createTextNode(` ${q.citation}`));
    btn.addEventListener("click", () => select(nb.id));
    li.append(btn);
    list.append(li);
  }
  panel.replaceChildren(close, h3, meta, body, h4, list);

  const v = scenePos(p);
  flyTo(new THREE.Vector3(v[0], v[1], v[2]));
}

function showMarker(p) {
  clearMarker();
  const [x, y, z] = scenePos(p);
  const group = new THREE.Group();
  const dot = new THREE.Mesh(
    new THREE.SphereGeometry(0.85, 18, 18),
    new THREE.MeshBasicMaterial({ color: 0xffffff }));
  dot.position.set(x, y, z);
  const ring = new THREE.Mesh(
    new THREE.RingGeometry(1.6, 1.85, 32),
    new THREE.MeshBasicMaterial({ color: 0x7dd3fc, side: THREE.DoubleSide, transparent: true, opacity: 0.85 }));
  ring.position.set(x, y, z);
  ring.lookAt(camera.position);
  group.add(dot, ring);
  scene.add(group);
  state.marker = group;
}

function clearMarker() {
  if (state.marker) { scene.remove(state.marker); state.marker = null; }
  if (state.lines) { scene.remove(state.lines); state.lines = null; }
}

function drawNeighbourLines(p, neighbours) {
  if (state.lines) { scene.remove(state.lines); state.lines = null; }
  const from = scenePos(p);
  const verts = [];
  for (const nb of neighbours) {
    const v = scenePos(state.bundle.points[nb.id]);
    verts.push(from[0], from[1], from[2], v[0], v[1], v[2]);
  }
  const geo = new THREE.BufferGeometry();
  geo.setAttribute("position", new THREE.Float32BufferAttribute(verts, 3));
  const lines = new THREE.LineSegments(geo, new THREE.LineBasicMaterial({
    color: 0x7dd3fc, transparent: true, opacity: 0.35 }));
  scene.add(lines);
  state.lines = lines;
}

function flyTo(target) {
  const offset = camera.position.clone().sub(controls.target);
  if (offset.lengthSq() < 1e-6) offset.set(0, 0.4, 1);
  offset.normalize().multiplyScalar(34);
  state.tween = {
    t0: performance.now(), dur: 650,
    fromPos: camera.position.clone(), toPos: target.clone().add(offset),
    fromTgt: controls.target.clone(), toTgt: target.clone(),
  };
}

function stepTween() {
  const t = Math.min(1, (performance.now() - state.tween.t0) / state.tween.dur);
  const e = t < 0.5 ? 2 * t * t : 1 - Math.pow(-2 * t + 2, 2) / 2;
  camera.position.lerpVectors(state.tween.fromPos, state.tween.toPos, e);
  controls.target.lerpVectors(state.tween.fromTgt, state.tween.toTgt, e);
  if (t >= 1) state.tween = null;
}

/* -------------------------------------------------------------- sidebar UI */

function renderMeta(bundle) {
  const m = bundle.meta;
  const bits = [];
  if (m.pages) bits.push(`${formatInt(m.pages)} pages`);
  bits.push(`${m.chapters} chapters`);
  bits.push(`${formatInt(m.words_total)} words`);
  bits.push(`${formatInt(m.unique_words)} unique words`);
  bits.push(`${m.dialogue_share_pct.toFixed(1)}% dialogue`);
  bits.push(`${formatInt(m.chunks)} chunks · ${m.dense_dim}-d ${m.dense_model}`);
  el("meta").textContent = `${m.input_format.toUpperCase()} input (${m.source}) — ` + bits.join(" · ");
}

function renderChapters(bundle) {
  const host = el("chapters");
  host.replaceChildren();
  bundle.chapters.forEach((c, i) => {
    const li = document.createElement("li");
    li.dataset.ch = c.index;
    const btn = document.createElement("button");
    btn.type = "button";
    const sw = document.createElement("span");
    sw.className = "swatch";
    sw.style.background = `hsl(${chapterHue(i)} 70% 60%)`;
    const name = document.createElement("span");
    name.textContent = c.short;
    const sub = document.createElement("span");
    sub.className = "sub";
    sub.textContent = `${formatInt(c.words)}w · ${c.dialogue_pct.toFixed(0)}%`;
    btn.append(sw, name, sub);
    btn.addEventListener("click", () => highlightChapter(c.index));
    li.append(btn);
    host.append(li);
  });
}

function highlightChapter(chIdx) {
  const same = state.chapter === chIdx;
  state.chapter = same ? null : chIdx;
  const attr = state.pointsObj.geometry.getAttribute("color");
  const base = state.baseColors;
  state.bundle.points.forEach((p, i) => {
    const on = state.chapter === null || p.ch === state.chapter;
    if (on) {
      attr.array[i * 3] = base[i * 3];
      attr.array[i * 3 + 1] = base[i * 3 + 1];
      attr.array[i * 3 + 2] = base[i * 3 + 2];
    } else {
      attr.array[i * 3] = 0.13; attr.array[i * 3 + 1] = 0.15; attr.array[i * 3 + 2] = 0.2;
    }
  });
  attr.needsUpdate = true;
  document.querySelectorAll("#chapters li").forEach((li) => {
    li.querySelector("button").classList.toggle("active", Number(li.dataset.ch) === state.chapter);
  });
  if (state.chapter !== null) {
    const mine = state.bundle.points.filter((p) => p.ch === state.chapter);
    const c = new THREE.Vector3();
    for (const p of mine) { const v = scenePos(p); c.add(new THREE.Vector3(v[0], v[1], v[2])); }
    c.divideScalar(mine.length);
    flyTo(c);
  }
}

function wireSearch(bundle) {
  const input = el("search");
  const results = el("results");
  let timer = null;
  const run = () => {
    const q = input.value.trim();
    results.replaceChildren();
    if (q.length < 3) return;
    for (const hit of keywordSearch(bundle.points, q, 8)) {
      const p = bundle.points[hit.id];
      const li = document.createElement("li");
      const btn = document.createElement("button");
      btn.type = "button";
      const score = document.createElement("span");
      score.className = "score";
      score.textContent = hit.score.toFixed(2);
      btn.append(score, document.createTextNode(` ${p.citation}`));
      btn.title = p.preview;
      btn.addEventListener("click", () => select(hit.id));
      li.append(btn);
      results.append(li);
    }
    if (!results.children.length) {
      const li = document.createElement("li");
      li.className = "caption";
      li.textContent = "no chunk contains those terms";
      results.append(li);
    }
  };
  input.addEventListener("input", () => { clearTimeout(timer); timer = setTimeout(run, 130); });
}

function wireHud() {
  el("reset").addEventListener("click", () => {
    state.chapter = null;
    highlightChapter(state.chapter);
    camera.position.set(0, 10, 54);
    controls.target.set(0, 0, 0);
  });
  el("spin").addEventListener("click", (e) => {
    controls.autoRotate = !controls.autoRotate;
    e.currentTarget.classList.toggle("on", controls.autoRotate);
  });
}

/* ------------------------------------------------------------- attributes */

const svgEl = (name, attrs = {}) => {
  const node = document.createElementNS(SVG_NS, name);
  for (const [k, v] of Object.entries(attrs)) node.setAttribute(k, v);
  return node;
};

function chartCard(label, svg) {
  const wrap = document.createElement("div");
  const cap = document.createElement("p");
  cap.className = "chart-label";
  cap.textContent = label;
  wrap.append(cap, svg);
  return wrap;
}

function barChart(items, w = 300, h = 66) {
  const svg = svgEl("svg", { viewBox: `0 0 ${w} ${h}`, class: "chart" });
  const hi = Math.max(...items.map((d) => d.v), 1);
  const bw = w / items.length;
  items.forEach((d, i) => {
    const bh = Math.max(1, (d.v / hi) * (h - 4));
    svg.append(svgEl("rect", {
      x: i * bw + 0.6, y: h - bh, width: Math.max(1, bw - 1.4), height: bh,
      fill: `hsl(${d.hue} 70% 60%)`, rx: 1.5,
    }));
  });
  return svg;
}

function lineChart(values, w = 300, h = 66) {
  const svg = svgEl("svg", { viewBox: `0 0 ${w} ${h}`, class: "chart" });
  const [lo, hi] = extent(values);
  const span = Math.max(Math.abs(lo), Math.abs(hi), 0.05);
  const x = (i) => (i / Math.max(1, values.length - 1)) * (w - 8) + 4;
  const y = (v) => h / 2 - (v / span) * (h / 2 - 6);
  svg.append(svgEl("line", {
    x1: 0, y1: h / 2, x2: w, y2: h / 2,
    stroke: "#3a4152", "stroke-width": 1, "stroke-dasharray": "3 3",
  }));
  svg.append(svgEl("polyline", {
    points: values.map((v, i) => `${x(i)},${y(v)}`).join(" "),
    fill: "none", stroke: "#7dd3fc", "stroke-width": 1.6,
  }));
  values.forEach((v, i) => svg.append(svgEl("circle", {
    cx: x(i), cy: y(v), r: 1.9, fill: "#7dd3fc",
  })));
  return svg;
}

function renderCharts(bundle) {
  const chs = bundle.chapters;
  const host = el("charts");
  host.replaceChildren(
    chartCard("Chapter length (words)", barChart(chs.map((c, i) => ({ v: c.words, hue: chapterHue(i) })))),
    chartCard("Dialogue share (%)", barChart(chs.map((c, i) => ({ v: c.dialogue_pct, hue: chapterHue(i) })))),
    chartCard("Emotional arc (VADER compound)", lineChart(chs.map((c) => c.sentiment))),
  );
}

function renderHeatmap(bundle) {
  const { names, counts } = bundle.characters;
  const chs = bundle.chapters;
  const cell = 13, gap = 1.5, labelW = 60, topH = 10;
  const w = labelW + chs.length * (cell + gap);
  const h = topH + names.length * (cell + gap);
  const svg = svgEl("svg", { viewBox: `0 0 ${w} ${h}`, class: "heat" });
  const max = Math.max(1, ...counts.flat());

  names.forEach((name, r) => {
    const label = svgEl("text", {
      x: 0, y: topH + r * (cell + gap) + cell * 0.82, class: "heat-label",
    });
    label.textContent = name;
    svg.append(label);
    counts[r].forEach((v, c) => {
      const k = v / max;
      const rect = svgEl("rect", {
        x: labelW + c * (cell + gap), y: topH + r * (cell + gap),
        width: cell, height: cell, rx: 2,
        fill: `rgb(${Math.round(28 + 227 * k)},${Math.round(28 + 155 * k)},${Math.round(38 + 20 * k)})`,
      });
      const title = svgEl("title", {});
      title.textContent = `${name} · ${chs[c].short}: ${v} mentions`;
      rect.append(title);
      svg.append(rect);
    });
  });
  el("heatmap").replaceChildren(svg);
}
